######################## default configuration ####################
baseURL = "https://mlwhiz.com/"
languageCode = "en-us"
title = "Helping You Learn Data Science!"
theme = "liva-hugo"
summaryLength = "10"
paginate = 10
disqusShortname = "mlwhiz"
timeout = 120000

pygmentsCodeFences = true
pygmentsUseClasses = false
pygmentsStyle = "native"


# TODO
enableGitInfo = true
enableRobotsTXT = true
[outputs]
  home = ["HTML", "RSS", "JSON"]

#ME
[markup.goldmark.renderer]
  unsafe = true


[sitemap]
  changefreq = "daily"
  filename = "sitemap.xml"
  priority = 1

[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = false
  disableXML = false
  minifyOutput = true
  [minify.tdewolff]
    [minify.tdewolff.css]
      decimals = -1
      keepCSS2 = true
    [minify.tdewolff.html]
      keepConditionalComments = true
      keepDefaultAttrVals = true
      keepDocumentTags = true
      keepEndTags = true
      keepQuotes = false
      keepWhitespace = false
    [minify.tdewolff.js]
    [minify.tdewolff.json]
    [minify.tdewolff.svg]
      decimals = -1
    [minify.tdewolff.xml]
      keepWhitespace = false

#ME
[frontmatter]
  date = ["date", "publishDate", "lastmod"]
  lastmod = [ "lastmod" , ":git", ":fileModTime"]
  publishDate = ["publishDate", "date"]
  expiryDate = ["expiryDate"]




############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/compressjscss/main.css"
  # [[params.plugins.css]]
  # URL = "plugins/bootstrap/bootstrap.min.css"
  # [[params.plugins.css]]
  # URL = "plugins/slick/slick.css"
  # [[params.plugins.css]]
  # URL = "plugins/themify-icons/themify-icons.css"
  # [[params.plugins.css]]
  # URL = "plugins/venobox/venobox.css"

  # JS Plugins
  # [[params.plugins.js]]
  # URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/compressjscss/main.js"
  # [[params.plugins.js]]
  # URL = "plugins/bootstrap/bootstrap.min.js"
  # [[params.plugins.js]]
  # URL = "plugins/slick/slick.min.js"
  # [[params.plugins.js]]
  # URL = "plugins/venobox/venobox.min.js"
  # [[params.plugins.js]]
  # URL = "plugins/search/fuse.min.js"
  # [[params.plugins.js]]
  # URL = "plugins/search/mark.js"
  # [[params.plugins.js]]
  # URL = "plugins/search/search.js"


############################## navigation ###############################
[menu]

  # main menu
  [[menu.main]]
  name = "About"
  URL = "about"
  weight = 1

  [[menu.main]]
  name = "Blog"
  URL = "blog"
  weight = 2


  [[menu.main]]
      identifier = "topic"
      name = "Topics"
      url = "/categories"
      weight = 4
      [[menu.main]]
          identifier = "deep-learning"
          name = "Deep Learning"
          url = "/categories/deep-learning"
          parent = "topic"
          weight = 3
      [[menu.main]]
          identifier = "natural-language-processing"
          name = "NLP"
          url = "/categories/natural-language-processing"
          parent = "topic"
          weight = 1
      [[menu.main]]
          identifier = "computer-vision"
          name = "Computer Vision"
          url = "/categories/computer-vision"
          parent = "topic"
          weight = 2
      [[menu.main]]
          identifier = "data-science"
          name = "DS/ML"
          url = "/categories/data-science"
          parent = "topic"
          weight = 4

      [[menu.main]]
          identifier = "awesome-guides"
          name = "My Best Content"
          url = "/categories/awesome-guides"
          parent = "topic"
          weight = 6

      [[menu.main]]
          identifier = "learning-resources"
          name = "Learning Resources"
          url = "/categories/learning-resources"
          parent = "topic"
          weight = 7
      [[menu.main]]
          identifier = "big-data"
          name = "Big Data"
          url = "/categories/big-data"
          parent = "topic"
          weight = 5

  # footer menu
  [[menu.footer]]
  name = "About"
  URL = "about"
  weight = 1

  [[menu.footer]]
  name = "Post"
  URL = "blog"
  weight = 2

  [[menu.footer]]
  name = "Contact"
  URL = "contact"
  weight = 3


#################### default parameters ################################
[params]
logo = "images/logo.png"
home = "Home"
# Meta data
opengraph = true # Enable OpenGraph if true
twitter_cards = true # Enable Twitter Cards if true
description = "Want to Learn Computer Vision and NLP? - MLWhiz"
author = "Rahul Agarwal"
# Google Analitycs
googleAnalitycsID = "UA-54777926-1"
# Contact Information
mobile = "+91-9711261345"
email = "rahul@mlwhiz.com"
location = "India, Bangalore"
# copyright
copyright = "Copyright &copy; 2020 [MLWhiz](https://mlwhiz.com) All Rights Reserved "

  # Preloader
  [params.preloader]
  enable = true
  preloader = "" # use .png , .svg or .gif format

  # search
  [params.search]
  enable = true

############################ news letter ########################
[params.newsletter]
enable = false
title = "Join Our Newsletter"
content = "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero"

############################# social site ########################


[[params.social]]
title = "linkedin"
icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
link = "https://www.linkedin.com/in/rahulagwl/"

[[params.social]]
title = "medium"
icon = "ti-book" # themify icon : https://themify.me/themify-icons
link = "https://mlwhiz.medium.com/"

[[params.social]]
title = "twitter"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/MLWhiz"

[[params.social]]
title = "facebook"
icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
link = "https://www.facebook.com/mlwhizblog"

[[params.social]]
title = "github"
icon = "ti-github" # themify icon : https://themify.me/themify-icons
link = "https://github.com/MLWhiz"
