baseurl = "/"
title = "MLWhiz"
languageCode = "en-us"
paginate = "10" # Number of posts per page
theme = "mainroad"
disqusShortname = "mlwhiz" # Enable comments by entering your Disqus shortname
googleAnalytics = "UA-54777926-1" # Enable Google Analytics by entering your tracking id
pygmentsCodeFences = true
pygmentsStyle = "monokai"


[outputs]
home = ["HTML","RSS"]

[mediaTypes]
[mediaTypes."application/rss"]
suffixes = ["xml"]
[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss"
baseName = "atom"


[Author] # Used in authorbox
  name = "Rahul Agarwal"
  bio = "John Doe's true identity is unknown. Maybe he is a successful blogger or writer. Nobody knows it."
  avatar = "img/avatar.png"

[Params]
  subtitle = "Deep Learning, Data Science and NLP Enthusiast" # Subtitle of your site. Used in site header
  description = "John Doe's Personal blog about everything" # Site description. Used in meta description
  copyright = "Rahul Agarwal" # copyright holder, otherwise will use site title
  opengraph = true # Enable OpenGraph if true
  twitter_cards = true # Enable Twitter Cards if true
  readmore = false # Show "Read more" button in list if true
  authorbox = false # Show authorbox at bottom of pages if true
  toc = true # Enable Table of Contents
  post_navigation = true # Show post navigation at bottom of pages if true
  # post_meta = ["date", "categories"] # Order of post meta information. Use ["none"] to turn off completely.
  postSections = ["post"] # the section pages to show on home page and the "Recent articles" widget
  #postSections = ["blog", "news"] # alternative that shows more than one section's pages
  #dateformat = "2006-01-02" # change the format of dates
  #mathjax = true # Enable MathJax
  #mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" # Specify MathJax path
  #mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config
  highlight = false
  customCSS = ["css/custom.css"] # Include custom CSS files
  logo = "images/M_2000.png"

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true
  nofollowLinks = true

[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "right"  # Configure layout for list pages
  single = false # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "recent"]
  #["search", "recent", "categories", "taglist", "social"]

[Params.widgets]
  recent_num = 10 # Set the number of articles in the "Recent articles" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)

[Params.widgets.social]
  # Enable parts of social widget
  facebook = "username"
  twitter = "username"
  instagram = "username"
  linkedin = "username"
  telegram = "username"
  github = "username"
  gitlab = "username"
  bitbucket = "username"
  email = "example@example.com"
  google_plus = "profileid"

[menu]

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
	identifier="archive"
	name="Archive"
	url="/archive"
	weight=3

[[menu.main]]
	identifier="rss"
	name="RSS"
	url="/atom.xml"
	weight=5