name: CI
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.82.0"

      - name: Build Hugo
        # remove --minify tag if you do not need it
        # docs: https://gohugo.io/hugo-pipes/minification/
        run: hugo --minify

      - name: Add CNAME
        run: echo "mlwhiz.com" >CNAME

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.TOKEN }}
          external_repository: mlwhiz/mlwhiz.github.io
          publish_dir: ./public
          #   keep_files: true
          user_name: mlwhiz
          user_email: rahul.374@gmail.com
          publish_branch: master
